# Generated by Django 3.2.5 on 2021-07-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('semester', models.CharField(choices=[('semester1', 'semester1'), ('semester2', 'semester2')], max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
