# Generated by Django 3.2.5 on 2021-07-07 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
    ]
