# Generated by Django 3.2.5 on 2021-07-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_subject_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary'), ('level1', 'level1'), ('level2', 'level2'), ('level3', 'level3'), ('level4', 'level4')], max_length=50, null=True),
        ),
    ]
