# Generated by Django 3.2.5 on 2021-07-07 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_subject_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='level',
        ),
    ]
