# Generated by Django 3.2.5 on 2021-07-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_subject_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminupload', models.FileField(upload_to='lecture_files')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
