# Generated by Django 3.2.5 on 2021-07-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='belongs_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='course.subject'),
            preserve_default=False,
        ),
    ]
