# Generated by Django 3.2.5 on 2021-07-08 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_lecture_belongs_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminupload', models.FileField(upload_to='lecture_files')),
                ('title', models.CharField(max_length=50)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminupload', models.FileField(upload_to='lecture_files')),
                ('title', models.CharField(max_length=50)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.subject')),
            ],
        ),
    ]
