# Generated by Django 3.2.5 on 2021-07-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_subjectcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='belongs_to',
        ),
        migrations.DeleteModel(
            name='Lab',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
