# Generated by Django 3.2.5 on 2021-07-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_auto_20210708_1711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectCategories',
        ),
    ]
