# Generated by Django 3.2.5 on 2021-07-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_delete_subjectcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='type',
            field=models.CharField(choices=[('lecture', 'lecture'), ('section', 'section'), ('lab', 'lab')], default='', max_length=40),
            preserve_default=False,
        ),
    ]
