# Generated by Django 3.2.5 on 2021-07-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_lecture_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=38),
        ),
    ]
