# Generated by Django 3.2.5 on 2021-07-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_complaint_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Complaint_text',
            field=models.TextField(max_length=200, verbose_name='Make a complaint with unknown identity in 200 characters'),
        ),
    ]
