# Generated by Django 3.2.5 on 2021-07-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_alter_subject_code'),
        ('home', '0005_alter_registraion_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registraion',
            name='subjects',
            field=models.ManyToManyField(to='course.Subject'),
        ),
    ]
