# Generated by Django 3.2.5 on 2021-07-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
