# Generated by Django 3.2.5 on 2021-07-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('primary level', 'primary level'), ('electronics & communications', 'electronics & communications'), ('computer engineering', 'computer engineering'), ('medical engineering', 'medical engineering'), ('electrical engineering', 'electrical engineering'), ('mechanical engineering', 'mechanical engineering')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
