# Generated by Django 3.2.5 on 2021-07-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(blank=True, choices=[('primary level', 'primary level'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('primary level', 'primary level'), ('electronics & communications', 'electronics & communications'), ('computer engineering', 'computer engineering'), ('medical engineering', 'medical engineering'), ('electrical engineering', 'electrical engineering'), ('mechanical engineering', 'mechanical engineering')], max_length=50, null=True),
        ),
    ]
