# Generated by Django 3.2.5 on 2021-07-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(blank=True, choices=[('doctor', 'doctor'), ('stuff', 'stuff'), ('student', 'student')], max_length=50, null=True),
        ),
    ]
